controller_manager:
  ros__parameters:
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - arm_j1
        - arm_j2
        - arm_j3
        - arm_j4
        - arm_j5
        - arm_j6
      interface_name: position

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
